### ISSUE TITLE
Prefered rule being collected after caret position

### ISSUE THREAD

**Issue by monxalo** [mike-lischke/antlr4-c3#13]
I use a grammar very similar to sql and i am getting the `tableRef` rule as a candidade on a case even tought it should only collect the valid tokens.

E.g.
```
deleteTable: DELETE TABLE tableRef WHERE EXPR;
tableRef: ID;
```
with `tableRef` as a prefered rule.

When typing `delete table ` with the caret at the last position the engine collects the candidate `tableRef`  as expected.

After typing the identifier for this rule `delete table items ` the engine now collects the next token `WHERE` correctly but it still returns the `tableRef` rule as a candidate. 

Is this working as intended?

Thanks

**Comment by monxalo** [comment]
Here's a stripped down version of the grammar and a test case:

```antlr
// syntax
deleteTable: DELETE TABLE tableRef WHERE EXPR;

tableRef: IDENTIFIER;

DELETE: 'delete';
TABLE: 'table';
WHERE: 'where';
EXPR: 'expr';

IDENTIFIER:             [a-zA-Z_] [a-zA-Z_0-9]*;

//Whitespace handling
NEWLINE:                '\r\n' | '\r' | '\n' ;
WHITESPACE:             [ \t]+ -> channel(HIDDEN);
```

```js
let inputStream = new ANTLRInputStream("delete table items ");
let lexer = new QLexer(inputStream);
let tokenStream = new CommonTokenStream(lexer);

let parser = new QParser(tokenStream);
let errorListener = new ErrorListener();
parser.addErrorListener(errorListener);
let tree = parser.deleteTable();

let core = new c3.CodeCompletionCore(parser);

// Ignore operators and the generic ID token.
core.ignoredTokens = new Set([
   QLexer.EOF
]);

core.preferredRules = new Set([
   QParser.RULE_tableRef
]);

core.showDebugOutput = true;
core.showRuleStack = true;
let candidates = core.collectCandidates(18, parser.tableRef());

console.log("Rules: " + candidates.rules.size);
console.log("Tokens: " + candidates.tokens.size);
```

**Comment by mike-lischke** [comment]
I see you pass in a parse context. Is that by intention? This will limit the search to that context and I wonder why you get the `WHERE` suggestion, but very like your caret position is outside of the passed in context, which is an invalid condition. If you have no specific reasons don't pass a context to `collectCandidates`.

**Comment by monxalo** [comment]
Hi @mike-lischke, thanks for responding.

Actually i tried both with and without the second argument for `collectCandidates` resulting in the same behaviour.

**Comment by nick-stephen** [comment]
Mike knows this much better than me, but does it produce the same results if the caret position is 19 rather than 18? At 18 you're just after the last character of 'items' but before the space, so it'd be reasonable syntactically to assume that maybe the word 'items' was incomplete and it could be completed... but maybe also it's complete and it'd be ok to move to the next token and suggest a 'where' ... at least that's the way I think it's working.

**Comment by mike-lischke** [comment]
Good point @nick-stephen, the lexer index should however be 7 (if I count correctly). Keep in mind hidden tokens count too.

@monxalo Look [in the graps tests](https://github.com/mike-lischke/antlr4-c3/blob/master/test/test.ts#L381), how I use the API.

**Comment by monxalo** [comment]
Thanks @mike-lischke but the index i'm giving is taking into account hidden tokens (spaces).
I'm assuming 18 is the correct index because i want followups token at the end of the input.

In my example i have:

|  d | e | l  | e | t |   e |  | t | a | b | l | e  |  | i | t | e | m | s |  |
| -  | -  | - | -  | - | -    | - | - |- | - | - | - | - | - | - | - | - | - | - |
| 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18

Isn't this the correct caret position?

**Comment by nick-stephen** [comment]
Hi Goncalo,

A token is a lexed entity, such as the token ‘delete’ or the token ‘table’. In between is a ‘space’ token. It’s not a character.

To get the token position you have to tokenize the input stream and see where the caret position is in terms of token number.

HTH

Nick

On 15/01/2018, 16:37, "Gonçalo Ferreira" <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks @mike-lischke<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mike-2Dlischke&d=DwMFaQ&c=uilaK90D4TOVoH58JNXRgQ&r=nrb6BBcaYzei5VLTFeRqBQ&m=3Caam2_901rugdJJCkaF3LQNdOa_qk7oQjVfDEz3ens&s=HCZCcwBkWNb-pApK-NpI7fWwgAqhHikva43zgBOY0hg&e=> but the index i'm giving is taking into account hidden tokens (spaces).
I'm assuming 18 is the correct index because i want followups token at the end of the input.

In my example i have:
d

e

l

e

t

e

t

a

b

l

e

i

t

e

m

s

0

1

2

3

4

5

6

7

8

9

10

11

12

13

14

15

16

17

18


Isn't this the correct caret position?

**Comment by monxalo** [comment]
Hi @nick-stephen, thanks for clarifying i was bit thrown off by the **Select the right caret position** section of the readme. 

I get the correct followup token `WHERE` but i still get the rule `tableRef` as candidate when passing  index 5 for the input `delete from items `. Shouldn't for this case only return the token as candidate?

**Comment by mike-lischke** [comment]
Index 5 is `EOF`? This token is not considered in C3. The engine collects all tokens upfront until it sees the given token index or EOF. The length of this token list is then taken as indicator if we reached the token position.

Also when you are at index 5 the caret is visually still at `items`, so you should still provide a candidates list for the table name (could be there's a table `itemspurchased`). Have you handled that already and it kicks in here? But even if you did it would not explain why you see both, the tableRef + WHERE. Only one of them should be returned from C3.

**Comment by kaidjohnson** [comment]
I'm running into the same scenario. I've created a dummy grammar, similar to the OP, that proves the inconsistency:
```
grammar BugTest;

test: LOREM IPSUM varRef ETC EOF ;
varRef: STRING ;

STRING: '"' ~["]+ '"' ;
LOREM: 'lorem' ;
IPSUM: 'ipsum' ;
ETC: 'etc' ;
```
And my test setup:
```
const collectCandidates = (input, index) => {
	const inputStream = new ANTLRInputStream(input);
	const lexer = new BugTestLexer(inputStream);
	const tokenStream = new CommonTokenStream(lexer);
	const parser = new BugTestParser(tokenStream);
	const errorListener = new BugTestErrorListener();
	parser.addErrorListener(errorListener);
	parser.test();

	const core = new c3.CodeCompletionCore(parser);

	core.ignoredTokens = new Set([ BugTestLexer.EOF ]);
	core.preferredRules = new Set([ BugTestParser.RULE_varRef ]);

	const candidates = core.collectCandidates(index);
	const keywords = [];
	const rules = [];

	for (let candidate of candidates.tokens) {
		const [token] = candidate;
		const displayName = parser.vocabulary.getDisplayName(token);

		keywords.push(displayName.slice(1, -1));
	}

	for (let candidate of candidates.rules) {
		switch (candidate[0]) {
			case BugTestParser.RULE_varRef:
				rules.push('"foo"');
				rules.push('"bar"');
				break;
		}
	}

	return {
		keywords,
		rules
	};
};
```
And the tests:
```
describe('Bug Test', () => {
	it('collects expected candidates', () => {
		expect(collectCandidates('lorem', 1).keywords).toEqual([
			'ipsum'
		]);

		expect(collectCandidates('lorem ipsum', 2)).toEqual({
			keywords: [],
			rules: ['"foo"', '"bar"']
		});

		expect(collectCandidates('lorem ipsum "foo"', 3)).toEqual({
			keywords: ['etc'],
			rules: []
		});
	});
});
```
And the test result:
```
  ● Bug Test › collects candidates

    expect(received).toEqual(expected)

    Difference:

    - Expected
    + Received

      Object {
        "keywords": Array [
          "etc",
        ],
    -   "rules": Array [],
    +   "rules": Array [
    +     "\"foo\"",
    +     "\"bar\"",
    +   ],
      }

      66 | 		});
      67 |
    > 68 | 		expect(collectCandidates('lorem ipsum "foo"', 3)).toEqual({
         | 		                                                  ^
      69 | 			keywords: ['etc'],
      70 | 			rules: []
      71 | 		});
```
The c3 engine is great! We've had really promising results so far. Other issues that we've noticed, we've generally been able to work around with some careful considerations of structure within the grammar itself, however this particular bug doesn't seem to go away no matter what we do. I've spent some time debugging and experimenting in the collectCandidates execution stack, but my limited experience with ANTLR is preventing me from really understanding the issue. With debugging enabled, I do see that the `STRING` is "consumed" but somehow it still ends up being a collected rule, even though it has already been applied. It seems to be that the `callStack`/`ruleStack` ends up containing the rule -- I do see that rules get pushed and popped off the stack after traversing the tree. I'm thinking that the preferredRule gets pushed to `candidates.rules` before it is supposed to be popped off of the stack.

Any additional insights would be much appreciated. I'm happy to propose a PR if I could get a bit of guidance on how to debug further.

**Comment by mike-lischke** [comment]
I'm afraid, I can't give you any useful advice off my head. This is an issue that requires more investigation. I'll try to free some time to look at this and your other problem @kaidjohnson.

**Comment by albyrock87** [comment]
Hi, I don't know if this helps, but I just tried to skip this command `if (!this.translateToRuleIndex(fullPath))` and It seems to work as expected.
Thank you for this awesome library!

**Comment by mike-lischke** [comment]
This seems to affect more people than what patch #7 fixes. We probably need to find a different solution for that other problem. So I will merge the fix from @kaidjohnson once its merge conflict is solved.

**Comment by nick-stephen** [comment]
ok, sounds good to me
