### ISSUE TITLE
Downgrade tsconfig target version until ES2020

### ISSUE THREAD

**Issue by viladimiru** [mike-lischke/antlr4-c3#131]
We have a problem with support for `safari v15` because it doesn't support static initialization blocks.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Static_initialization_blocks#browser_compatibility

I think changing tsconfig target to ES2020 might fix the issue. Would you consider making that change?

![telegram-cloud-photo-size-2-5206549795517358449-y](https://github.com/mike-lischke/antlr4-c3/assets/26850586/c3cdf731-85ac-462f-9e23-3814a66abde6)

https://github.com/mike-lischke/antlr4-c3/blob/main/tsconfig.json#L5

**Comment by mike-lischke** [comment]
You can use a bundler like webpack or esbuild to create a compatible build. It makes no sense to force an older ES version on all users, especially considering that almost all use of the library is done through a bundler.
