### ISSUE TITLE
Make C++ port thread safe

### ISSUE THREAD

**Issue by vityaman** [mike-lischke/antlr4-c3#139]
It seems to me that the current implementation is not thread safe because of [a global variable](https://github.com/mike-lischke/antlr4-c3/blob/32a793cecb39909352528d13f858219397801aac/ports/cpp/source/antlr4-c3/CodeCompletionCore.cpp#L58) used in [rule processing](https://github.com/mike-lischke/antlr4-c3/blob/32a793cecb39909352528d13f858219397801aac/ports/cpp/source/antlr4-c3/CodeCompletionCore.cpp#L526). As I understand, this `std::map` is some kind of cache of `FollowSetsPerState`.

This was one of the reasons for starting work on the C++ port in #132.

`std::map` is not thread safe, so it should be guarded by some `std::mutex` or be made `thread_local`, like `DFA` cache in `ANTLRv4`.

It should be noticed that I did these conclusions only by reading the code and did not test it, so the task should be studied firstly.

**Comment by mike-lischke** [comment]
Correct. Since TypeScript single threaded there's no need to make global variables (caches etc.) thread safe. For languages like Java and C++ this must be added explicitly. The easiest way is probably to use `thread_local` (C++) or `ThreadLocal<>`(Java).
