### ISSUE TITLE
npm test failing 

### ISSUE THREAD

**Issue by pluthraarkin** [mike-lischke/antlr4-c3#14]
Hi Mike, 

I downloaded the source. I executed npm install and then npm tests, but the test cases failed 

npm test

> antlr4-c3@1.1.6 test /Users/pluthra/repo/antlr4-c3-master
> tsc --version && tsc && mocha out/test

Version 2.3.4
test/CPP14Lexer.ts(8,5): error TS2305: Module '"/Users/pluthra/repo/antlr4-c3-master/node_modules/antlr4ts/index"' has no exported member 'ATN'.
test/CPP14Lexer.ts(9,5): error TS2305: Module '"/Users/pluthra/repo/antlr4-c3-master/node_modules/antlr4ts/index"' has no exported member 'ATNDeserializer'.
test/CPP14Lexer.ts(12,5): error TS2305: Module '"/Users/pluthra/repo/antlr4-c3-master/node_modules/antlr4ts/index"' has no exported member 'LexerATNSimulator'.
test/CPP14Lexer.ts(18,10): error TS2305: Module '"/Users/pluthra/repo/antlr4-c3-master/node_modules/antlr4ts/index"' has no exported member 'Utils'.
test/CPP14Parser.ts(7,2): error TS2305: Module '"/Users/pluthra/repo/antlr4-c3-master/node_modules/antlr4ts/index"' has no exported member 'ATN'.
test/CPP14Parser.ts(8,5): error TS2305: Module '"/Users/pluthra/repo/antlr4-c3-master/node_modules/antlr4ts/index"' has no exported member 'ATNDeserializer'.
test/CPP14Parser.ts(13,5): error TS2305: Module '"/Users/pluthra/repo/antlr4-c3-master/node_modules/antlr4ts/index"' has no exported member 'ParserATNSimulator'.
test/CPP14Parser.ts(14,5): error TS2305: Module '"/Users/pluthra/repo/antlr4-c3-master/node_modules/antlr4ts/index"' has no exported member 'ParseTreeListener'.
test/CPP14Parser.ts(15,5): error TS2305: Module '"/Users/pluthra/repo/antlr4-c3-master/node_modules/antlr4ts/index"' has no exported member 'ParseTreeVisitor'.
test/CPP14Parser.ts(19,5): error TS2305: Module '"/Users/pluthra/repo/antlr4-c3-master/node_modules/antlr4ts/index"' has no exported member 'TerminalNode'.
test/CPP14Parser.ts(487,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(523,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(602,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(641,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(724,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(889,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(927,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(965,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(1016,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(1136,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(1175,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(1224,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(1270,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(1713,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(1738,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(1834,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(1973,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(2009,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(2117,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(2146,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(2181,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(2326,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(2379,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(2447,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(2478,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(3380,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(3427,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(3478,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(3645,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(3670,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(3818,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(3910,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(3946,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(4046,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(4121,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(4199,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(4317,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(4356,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(4394,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(4486,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(4574,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(4661,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(4756,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(4843,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(4887,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(5005,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(5042,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(5067,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(5094,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(5191,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(5242,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(5278,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(5314,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(5339,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(5386,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(5460,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(5511,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(5562,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(5735,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(5790,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(5841,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(5947,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(5972,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(6034,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(6128,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(6178,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(6229,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(6320,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(6363,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(6388,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(6427,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(6452,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(6491,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(6530,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(6574,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(6618,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(6660,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(6694,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(6719,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(6752,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(6787,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(6849,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(6901,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(6934,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(7056,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(7104,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(7292,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(7327,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(7366,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(7395,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(7420,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(7519,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(7642,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(7677,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(7720,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(7896,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(7965,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(8002,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(8120,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(8155,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(8191,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(8227,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(8263,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(8298,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(8357,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(8561,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(8710,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(8836,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(8964,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(9022,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(9096,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(9141,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(9183,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(9359,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(9415,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(9454,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(9494,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(9586,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(9621,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(9646,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(9682,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(9795,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(9969,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(10131,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(10167,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(10195,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(10306,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(10408,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(10457,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(10482,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(10518,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(10545,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(10580,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(10615,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(10642,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(10706,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(10762,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(10801,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(10828,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(10873,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(10970,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(11009,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(11199,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(11239,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(11315,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(11424,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(11471,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(11529,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(11567,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(11598,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(11627,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(11667,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(11702,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(11735,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(11815,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(11850,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(11890,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(12014,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(12059,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(12086,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(12115,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(12486,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(12565,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(12601,3): error TS2346: Supplied parameters do not match any signature of call target.
test/CPP14Parser.ts(12626,3): error TS2346: Supplied parameters do not match any signature of call target.
test/ExprLexer.ts(5,5): error TS2305: Module '"/Users/pluthra/repo/antlr4-c3-master/node_modules/antlr4ts/index"' has no exported member 'ATN'.
test/ExprLexer.ts(6,5): error TS2305: Module '"/Users/pluthra/repo/antlr4-c3-master/node_modules/antlr4ts/index"' has no exported member 'ATNDeserializer'.
test/ExprLexer.ts(9,5): error TS2305: Module '"/Users/pluthra/repo/antlr4-c3-master/node_modules/antlr4ts/index"' has no exported member 'LexerATNSimulator'.
test/ExprLexer.ts(15,10): error TS2305: Module '"/Users/pluthra/repo/antlr4-c3-master/node_modules/antlr4ts/index"' has no exported member 'Utils'.
test/ExprParser.ts(4,2): error TS2305: Module '"/Users/pluthra/repo/antlr4-c3-master/node_modules/antlr4ts/index"' has no exported member 'ATN'.
test/ExprParser.ts(5,5): error TS2305: Module '"/Users/pluthra/repo/antlr4-c3-master/node_modules/antlr4ts/index"' has no exported member 'ATNDeserializer'.
test/ExprParser.ts(10,5): error TS2305: Module '"/Users/pluthra/repo/antlr4-c3-master/node_modules/antlr4ts/index"' has no exported member 'ParserATNSimulator'.
test/ExprParser.ts(11,5): error TS2305: Module '"/Users/pluthra/repo/antlr4-c3-master/node_modules/antlr4ts/index"' has no exported member 'ParseTreeListener'.
test/ExprParser.ts(12,5): error TS2305: Module '"/Users/pluthra/repo/antlr4-c3-master/node_modules/antlr4ts/index"' has no exported member 'ParseTreeVisitor'.
test/ExprParser.ts(16,5): error TS2305: Module '"/Users/pluthra/repo/antlr4-c3-master/node_modules/antlr4ts/index"' has no exported member 'TerminalNode'.
test/ExprParser.ts(73,3): error TS2346: Supplied parameters do not match any signature of call target.
test/ExprParser.ts(114,3): error TS2346: Supplied parameters do not match any signature of call target.
test/ExprParser.ts(273,3): error TS2346: Supplied parameters do not match any signature of call target.
test/ExprParser.ts(298,3): error TS2346: Supplied parameters do not match any signature of call target.

Thanks,
Priyanka

**Comment by mike-lischke** [comment]
Looks like antlr4ts is not properly installed. Can you check that? It should be added by `npm install` (and it works like that in Travis-CI.

**Comment by pluthraarkin** [comment]
Thanks Mike, I made changes to generated Lexer and Parser basically removing the <Type> from @RuleVersion like you have done and it worked. Can this be fixed in generation?

**Comment by mike-lischke** [comment]
Hmm, not sure what you changed. Can you explain a bit more?

**Comment by pluthraarkin** [comment]
So basically the generated code I have to remove the Parameterised Types, like below
@RuleVersion<PrimaryexpressionContext>(0)  changed to @RuleVersion(0) .

Also, do you have any idea on how to make this work with es5 as our project has es5 as the target. I get below errorwith es5
#Error Class constructor Lexer cannot be invoked without 'new'.

**Comment by pluthraarkin** [comment]
It works with es6 target but fails with es5 with this error(#Error Class constructor Lexer cannot be invoked without 'new') in the generated Lexer class in the constructor when it tries to invoke super.
export class ExprLexer extends Lexer {
....
constructor(input: CharStream) {
		super(input);
		this._interp = new LexerATNSimulator(ExprLexer._ATN, this);
	}

**Comment by mike-lischke** [comment]
Sorry for comming back so late to this issue. I just published a new version with the new antlr4ts 0.5.0 alpha 1 release. Can you please check if you still see this issue?
