### ISSUE TITLE
I want to know about something about IGNORE_TOKENS and PREFERRED_RULES

### ISSUE THREAD

**Issue by pdxzzz** [mike-lischke/antlr4-c3#159]
1. **IGNORE_TOKENS**:  
   If I add a large number of token types to `IGNORE_TOKENS`, will it impact the normal operation of the parser, or will it only act as a filter for the tokens collected during the parsing process?

2. **PREFERRED_RULES**:  
   I’ve added some rules to `PREFERRED_RULES`, and it seems to filter out certain tokens, but I’m not fully clear on its exact role.

**Comment by pdxzzz** [comment]
Thank you in advance for any clarification or insights you can provide on these topics! I appreciate your help in advance!

**Comment by mike-lischke** [comment]
1. This is list is just a filter. It's queried whenever a token is about to be added to the results and its token type is in that list, nothing happens.
2. To make handling of the results easier only indexes for rules in the preferred rules list are returned. Any other is just ignored. So you can be sure you only get rule indexes back which you have mentioned in the preferred rules list (if they are viable candidates).

**Comment by mike-lischke** [comment]
The returned rule candidates are determined from tokens, interpreted in their context (e.g. an ID token, which is part of a parser rule that wants a variable name is converted to a variable name result). So yes, if a token is part of a rule, the rule "wins".

**Comment by pdxzzz** [comment]
Thank you for your answer, but I am still not clear enough about it. So I presented my grammar files and actual problems.
**Here is the source address of my grammar file**
[https://github.com/antlr/grammars-v4/blob/master/sql/mysql/Positive-Technologies/MySqlParser.g4](url)
![image](https://github.com/user-attachments/assets/fdb5e5e7-477b-4588-bd27-01ac7581c6f8)
![image](https://github.com/user-attachments/assets/844d87d6-bcb0-4d07-b4c9-a9d63b1f4040)
![image](https://github.com/user-attachments/assets/dff02756-6451-4eb1-bcf0-37130e1e42e1)
![image](https://github.com/user-attachments/assets/6e213f1f-9395-4e13-979c-0eb18c5a3308)
![image](https://github.com/user-attachments/assets/aaf10f94-351a-4e39-a5ab-3e44b44f7887)
![image](https://github.com/user-attachments/assets/29127f5f-1989-4407-aca7-ab5374dfeea3)
![image](https://github.com/user-attachments/assets/4be448ba-1f5d-4210-973d-54e6056229e0)
![image](https://github.com/user-attachments/assets/0bbb5c77-448b-40e1-9bc4-eba0a3a519e0)
![image](https://github.com/user-attachments/assets/6623634c-89db-4cea-994b-584864509c1c)

**My Test**
~~~sql
select * from   {$cursor}
~~~
When I was conducting this test, I found that if I added `RULE_tableName` to `PREFERRED-RULES`, the results I collected through CandidatesCollections. tokens would be very clean, but if I didn't add that rule too much, I would collect a lot of irrelevant results.

So does this indicate that 'PREVERED-RULES' has an impact on the collection results of tokens?

Although I have been working hard to read the source code, it seems that I still haven't understood this matter. I hope to receive your answer. Thank you very much!

**Comment by mike-lischke** [comment]
> So does this indicate that 'PREVERED-RULES' has an impact on the collection results of tokens?

I answered you that question already in my last comment.

**Comment by pdxzzz** [comment]
> I answered you that question already in my last comment.

I'm sorry about this, I didn't understand what you meant. I feel like I need to debug the code more carefully to understand what you mean. I'm very sorry

**Comment by mike-lischke** [comment]
No worries. This is a complex matter. However I cannot analyze your specific situation, to help you with general problems. I think I answered your initial question by now. Regards.

**Comment by pdxzzz** [comment]
Thank you very much ！
