### ISSUE TITLE
Grammar and generated files can be inconsistent

### ISSUE THREAD

**Issue by vityaman** [mike-lischke/antlr4-c3#162]
Currently we commit antlr4 generated sources, but do not check for grammar and generated sources consistency. So contributor is able to update grammar, but forget to generate sources before sending a pull request. Then maintainer can forget to check it and merge breaking changes. 

I propose either not to commit generated sources (generate them during GitHub Workflow) or add some GitHub Workflow check that will ensure that current committed sources match with generated sources.

I can do it by myself.

**Comment by mike-lischke** [comment]
You are right, generated code should not be in a repo. Don't know how it ended up here, but it needs to be taken out.

**Comment by vityaman** [comment]
@mike-lischke, then I will delete generated sources and fix workflows tomorrow.

**Comment by mike-lischke** [comment]
Fixed by patch #163
