### ISSUE TITLE
Support antlr4ts@0.5.0-alpha.1

### ISSUE THREAD

**Issue by jackandjohn** [mike-lischke/antlr4-c3#19]
When I try out antlr4-c3 in my project，I get the following error:
![image](https://user-images.githubusercontent.com/10008741/50382468-db190d00-06da-11e9-82b8-52967cf6b26c.png)

![image](https://user-images.githubusercontent.com/10008741/50382474-0f8cc900-06db-11e9-9525-08efe0436eda.png)

My package.json is shown below:
```
{
  "scripts": {
    "build": "webpack --config webpack.config.js --watch",
    "antlr4ts": "antlr4ts -visitor src/parser/calculator.g4"
  },
  "dependencies": {
    "antlr4-c3": "^1.1.8",
    "antlr4ts": "^0.5.0-alpha.1"
  },
  "devDependencies": {
    "antlr4ts-cli": "^0.5.0-alpha.1",
    "ts-loader": "^5.3.1",
    "typescript": "^3.2.2",
    "webpack": "^4.28.0",
    "webpack-cli": "^3.1.2"
  }
}
```

Is c3 support antlr4ts@0.5.0-alpha.1？

Thanks!

**Comment by mike-lischke** [comment]
The unit tests run fine with the 0.5.0 alpha. Can you look where the `-1` comes from?

**Comment by mike-lischke** [comment]
antlr4-c3 works well with latest antlr4ts.
