### ISSUE TITLE
NPM package install attempts to build tests when installing as dependency, generating errors

### ISSUE THREAD

**Issue by BurtHarris** [mike-lischke/antlr4-c3#2]
Transferred from issue tunnelvisionlabs/antlr4ts#304

Repro *(from an empty directory)*:
```
npm install antlr4-graps
```
Errors generated:
```
> antlr4-c3@1.0.6 postinstall C:\try\304\node_modules\antlr4-c3
> tsc
test/test.ts(10,40): error TS2307: Cannot find module 'chai'.
test/test.ts(87,1): error TS2304: Cannot find name 'describe'.
test/test.ts(89,3): error TS2304: Cannot find name 'describe'.
test/test.ts(90,5): error TS2304: Cannot find name 'it'.
test/test.ts(168,5): error TS2304: Cannot find name 'it'.
test/test.ts(208,5): error TS2304: Cannot find name 'it'.
test/test.ts(219,5): error TS2304: Cannot find name 'it'.
test/test.ts(233,5): error TS2304: Cannot find name 'it'.
test/test.ts(277,3): error TS2304: Cannot find name 'describe'.
test/test.ts(278,5): error TS2304: Cannot find name 'it'.
test/test.ts(338,5): error TS2304: Cannot find name 'it'.
test/test.ts(403,3): error TS2304: Cannot find name 'describe'.
test/test.ts(404,5): error TS2304: Cannot find name 'it'.
test/test.ts(412,5): error TS2304: Cannot find name 'it'.
```
Analysis:

This is happening because the *postinstall* step for **antlr4-c3** in NPM is attempting to build the unit tests.  I'm no expert in node development, but what I tried to do in building **antlr4ts** was exclude development-time dependencies (like the tests).

**Comment by BurtHarris** [comment]
I'm going to have a look at this project (seems interesting Mike) and see if I can make a more specific suggestion on how to handle this.

**Comment by mike-lischke** [comment]
Hmm, it's not that easy to find a good compact description what has to go where to make this publishing process (and the installation on the user's side) as painless as possible. However, I believe I have it now how it should be.

@millergarym ^
