### ISSUE TITLE
Preferred rules precedence

### ISSUE THREAD

**Issue by ghost** [mike-lischke/antlr4-c3#20]
I have a grammar like this:

```
identifier: IDENTIFIER;
binary_operation: identifier 'op' operand;
```

I'm interested in `identifier` **then** `binary_operation`. I expected that if I types just an identifier, the `CandidatesCollection.rulePositions` should contains just preferred `identifier` rule; if I types an identifier then `op` then an operand,  the `CandidatesCollection.rulePositions` should contains `binary_operation` rule.

But in reality, the `binary_operation` rule always overrides the `identifier` rule. That is if I type just an identifier, the `rulePositions` contains `binary_operation` rule.

I tried to use `LinkedHashSet` to rearrange the preferred rules but it didn't seem to work.

**Comment by mike-lischke** [comment]
How did you specify the preferred rules list? The rule invocation stack is searched through from lowest to highest index. Hence when you get to a token which is part of `identifier` this rule will be returned (provided `identifier` is part of the preferred rules set).
