### ISSUE TITLE
How to correctly use collectCandidates()?

### ISSUE THREAD

**Issue by omurbekjk** [mike-lischke/antlr4-c3#21]
Say I have mysql grammar, and want to get autocomplete after `select ` query.
Simple grammar: 
```
query: SELECT tableRef;
tableRef: ID;
ID
    : [a-zA-Z] [a-zA-Z0-9_]*
    ;
```
How should I correctly find `caretTokenIndex`?
const candidates = core.collectCandidates('select'.length-1); OR const candidates = core.collectCandidates(0);

**Comment by mike-lischke** [comment]
A token index is the index of the token in the token stream, not a character index. What you first have to do is to take your caret position and find the correct token index for that. You can do that by simply iterating over the token stream and find the token that encloses the caret position.

**Comment by omurbekjk** [comment]
Say I have this  `select name from u|sers` query and caret position is in the last token.
By iterating over the token stream, I need to find the token index that has caret position right?
```
let index=-1;
for(let token of tokenStream.tokens) {
    console.log(token.type + " : " + parser.symbolicNames[token.type]);
// TODO find caret index
}
// index = 3 
```

**Comment by mike-lischke** [comment]
Correct.

**Comment by omurbekjk** [comment]
I noticed that tokens are protected `protected tokens: Token[];` in ts. How to get tokens in ts do you know?

**Comment by mike-lischke** [comment]
Easy, check the [C3 source](https://github.com/mike-lischke/antlr4-c3/blob/master/src/CodeCompletionCore.ts#L112) how it is done there.
