### ISSUE TITLE
support antlr4 javascript runtime

### ISSUE THREAD

**Issue by futurepaycc** [mike-lischke/antlr4-c3#22]
as title,for browser use case
any plan?

**Comment by mike-lischke** [comment]
That mostly depends on antlr4-c3, but generally speaking: the code is Typescript and can be transpiled to JS.

**Comment by futurepaycc** [comment]
it's not the problem of typescript,but antlr4ts not compatible with browser very well,just like 
[https://github.com/tunnelvisionlabs/antlr4ts/issues/326](url)....
so if antlr4-c3 swith to antlr4 javascript runtime is good for many web editors

**Comment by mike-lischke** [comment]
Sorry, I mistyped my first answer. The antlr4ts project is controlled by Sam Harwell and not by me. If that runtime doesn't support browsers I can't do anything to make it work.
