### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by kaidjohnson** [mike-lischke/antlr4-c3#28]
Hi @mike-lischke 

I wasn't sure what process you follow to get a new release cut, but I'd like to be able to consume the fix for #13 via npm with a version bump.

Thanks!

**Comment by mike-lischke** [comment]
I can probably do a new release next weekend.

**Comment by kaidjohnson** [comment]
For what it's worth, I would be happy to help move this along. Let me know where and how I could be useful here.

**Comment by mike-lischke** [comment]
Sorry, simply forgot it last week. The new release is out now.
