### ISSUE TITLE
No way to get starting candidates on empty input

### ISSUE THREAD

**Issue by unsupervisednn** [mike-lischke/antlr4-c3#39]
Without suppling input I would like to get valid candidates for completion. The current way with `parser.collectCandidates(tokenIndex)` requires that there be a token index which doesn't exist for the empty string.

**Comment by alessiostalla** [comment]
Can't you pass -1 as the token index?

**Comment by mike-lischke** [comment]
-1 will not work, but 0 should. There's always at least one token in the token stream (EOF).
