### ISSUE TITLE
ANTLR version?

### ISSUE THREAD

**Issue by alessiostalla** [mike-lischke/antlr4-c3#43]
Thanks for the library. I'm having trouble using it with ANTLR 4.7.0 (the latest to have published TypeScript types).
However, I'm finding API mismatches (can get more specific if you need). What ANTLR4 version is this targeting?

**Comment by mike-lischke** [comment]
Usually I target the latest antlr4ts release, which is "^0.5.0-alpha.3" currently (see also package.json).

**Comment by alessiostalla** [comment]
Oh, nice, thanks! I will try with it instead.

**Comment by eskimoblood** [comment]
How hard would it be to port your code to use the antlr4 npm package. As far as I understand the antlr4ts has problems to run in a browser.

**Comment by mike-lischke** [comment]
The ANTLR4 npm package has no Typescript target.

**Comment by eskimoblood** [comment]
What I mean is, if we would try to rewrite your library for antlr4. Is this possible, and would it be just adopting calls for a slightly different API, or would it be a totally rewrite cause antlr4 and antlr4ts are to different.

**Comment by mike-lischke** [comment]
Unfortunately, the authors of antlr4ts decided to optimize their target in a way that makes it partially incompatible with the stock ANTLR4 lib. But  with some effort you can rewrite C3 to use the ANTLR4 Javascript target instead. See also the[ C#](https://github.com/mike-lischke/antlr4-c3/tree/master/ports/c%23) and [Java](https://github.com/mike-lischke/antlr4-c3/tree/master/ports/java) ports of C3.

**Comment by sobolewsk** [comment]
For anyone interested, here is a quick'n'dirty port to the ANTLR4 TS runtime: https://github.com/sobolewsk/antlr4-c3ts/tree/branches/antrlts-runtime
