### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by ftomassetti** [mike-lischke/antlr4-c3#49]
Hi Mike,
first of all thank you for writing this amazing project.

I see that the build is failing, the Java port is three years old and the last version is unreleased.

I was wondering about the status of the project and if you would be interesting in any help on this project.

**Comment by mike-lischke** [comment]
This project is currently in maintenance mode, which means bugs will be fixed from time to time and pull requests will be accepted. No new development is under way.

The build fails only for one target (Node.js 6) which seems to have a problem with the Mocha update. I should probably only run tests on the latest stable platform.

Regarding the ports: this is entirely up to the original writers. I cannot maintain ports of the library to other languages. I haven't got any further PRs for the Java ports, so consequently nothing changed there for a while.

**Comment by ftomassetti** [comment]
Thank you Mike! 
If we find the time would you consider some PRs to the java port, to update it to ANTLR 4.8 and maybe to release it on bintray, so that it can be easier to use in projects?

**Comment by mike-lischke** [comment]
Sure, absolutely.
