### ISSUE TITLE
Request for latest release to npm

### ISSUE THREAD

**Issue by soneymathew** [mike-lischke/antlr4-c3#53]
Hello @mike-lischke 👋 ,

Please can you help publish the latest version to [npm](https://www.npmjs.com/package/antlr4-c3) ? 🙏 

Lot of goodies since the last release 🥳  
https://github.com/mike-lischke/antlr4-c3/compare/1.1.12...master

Thanks,
Soney

**Comment by mike-lischke** [comment]
Done!
