### ISSUE TITLE
translateToRuleIndex addNew doesn't really add, it replaces

### ISSUE THREAD

**Issue by alessiostalla** [mike-lischke/antlr4-c3#55]
translateToRuleIndex checks for a rule to already be present in order to avoid adding a duplicate entry.

However, entries are in a map, not a list, so no duplicates are possible, and what really happens is that each new found path overwrites the previous one. IMO this should be clarified:

- if the intention is to return only one path, then it makes no sense to perform a linear search on a map, just store the latest path (another option could be to store only the first and cut the search early if possible)
- if the intention is to return multiple paths, then it makes no sense to use a map from index to path; candidate.rules should then be a map from index to a list of paths (and then it makes sense to perform a linear search to avoid including the same path twice).

This could be controlled by a flag, as one user might want to stop searching as early as possible, while another might want to collect all the paths. But as it is now, all paths are examined but only the latest is returned, which is a waste.

**Comment by mike-lischke** [comment]
This is a valid point and tbh. I'm not sure which way to go here. Does it have merits to store all paths over which a specific rule was found? I'm not even using a single path in my projects. It is more the wish to provide all information to c3 user in case it is useful, why I included that detail. But I haven't found a real world example to take advantage of the stored path.

So, I'm open for both approaches, or even remove the path entirely.

**Comment by alessiostalla** [comment]
Actually I've never used the path either, but maybe there are more advanced users out there :)

**Comment by mike-lischke** [comment]
Well, even though it's not the best approach as it is implemented now, I'd not touch it until someone comes up with a real need. Thanks for bringing it up anyway.
