### ISSUE TITLE
Release version 1.1.14

### ISSUE THREAD

**Issue by alessiostalla** [mike-lischke/antlr4-c3#56]
In our codebase, we're using antlr4-c3 from the master branch as it fixes some issues for us. However, this complicates our build. Would it be possible to release a 1.1.14 version? Is something missing for it (e.g. some critical bug fix)? I'm available to dedicate some time to this if it can be useful.

**Comment by mike-lischke** [comment]
Yes, I think this can be done next weekend.

**Comment by mx2323** [comment]
currently working with antlr4-c3 with alessio and this is a blocker for us. thanks mike ~!

**Comment by mike-lischke** [comment]
Done as version 1.1.15.
