### ISSUE TITLE
Release new library for Java port

### ISSUE THREAD

**Issue by floynn-shopify** [mike-lischke/antlr4-c3#57]
Hi,
I wonder if you plan to do new release of Java port library? The latest version I found here https://mvnrepository.com/artifact/com.vmware.antlr4-c3/antlr4-c3 is `1.1` which doesn’t look like have this fix https://github.com/mike-lischke/antlr4-c3/pull/27 . 

It would be great if you can make new release so users will be able to consume library with latest fixes.

**Comment by mike-lischke** [comment]
I don't maintain other languages than Typescript and C++., but I will accept pull requests to update any port.

**Comment by floynn-shopify** [comment]
I didn’t actually mean to ask to update anything right now I was wondering if you can make a new release.
Last release of java port was back in 2017 https://github.com/mike-lischke/antlr4-c3/releases/tag/ports%2Fjava%2F1.1 and it’s different from what current code looks like. Maybe @nick-stephen  knows more since it looks like @nick-stephen made last release java port.

**Comment by mike-lischke** [comment]
Meanwhile several releases have been issued (the last one today). So I think we can close this issue.
