### ISSUE TITLE
Help Wanted: Not getting rule candidates

### ISSUE THREAD

**Issue by kostyay** [mike-lischke/antlr4-c3#59]
Hi
I've build a very simple lexer parser that is supposed to match simple syntax such as the one below

`$.arg1.arg2.arg3`

```
parser grammar MyTmplParser; 
options { tokenVocab=MyTmplLexer; }

contextVariable: DOT argumentRef;
argumentRef: IDENTIFIER;

contextVariablesRef: (contextVariable)+;
templateExpression: (JSONPATH_START contextVariablesRef)*;
root: templateExpression;
```

```
lexer grammar MyTmplLexer;

WS: [\t\r\n] -> channel(HIDDEN);
SPACE: ' ' -> channel(HIDDEN);
DOT: '.';
IDENTIFIER : (ALPHA | DIGIT)+;
JSONPATH_START: '$';

fragment
    ALPHA : [a-zA-Z] ;
fragment
    DIGIT : [0-9] ;
```

Parsing works fine:
![image](https://user-images.githubusercontent.com/3660553/131568481-33e160d1-5134-4fbd-bfe7-c3570c3b19b0.png)

I have some symbols predefined.
I would like to auto complete `argumentRef`.
The prefix of `JSONPATH_START` in templateExpression seems to break the auto complete logic.
If I were to define it as `templateExpression: (contextVariablesRef)*;` it works as expected. I don't understand what I'm doing wrong. Any pointers will be helpful

Code looks like this:
```javascript
    const preferred = [ MyTmplParser.RULE_argumentRef ];

    core.ignoredTokens = new Set([]);
    core.preferredRules = new Set(preferred);
    let candidates = core.collectCandidates(position.index);
```

This is the output that I get for input `"$.a.b"` for "token position" 2:
```
Error Count: 0
Token position: 2 - a

States processed: 0


Collected rules:



Collected tokens:




```

**Comment by mike-lischke** [comment]
Your debug output looks like you haven't even started processing the input. Is your input stream still alive at the point you call `collectCandidates`? Print the tokens list you can get from the lexer, to see if everything is as expected, right before you call `collectCandidates`.

Also you could just step into the code of that function to see why c3 exist out early and doesn't even walk a single ATN state.
