### ISSUE TITLE
RoutineSymbol returnType is inaccessible

### ISSUE THREAD

**Issue by NorthNick** [mike-lischke/antlr4-c3#62]
The `returnType` of [RoutineSymbol](https://github.com/mike-lischke/antlr4-c3/blob/c22d542fa8e79874030c4fa254ad8ababdb495f7/src/SymbolTable.ts#L853) is potentially useful, but the class variable is marked as private so I'm unclear how you would use it. Should the variable be public, or is there a way of getting at it that I'm missing?

**Comment by mike-lischke** [comment]
That should indeed be public.

**Comment by NorthNick** [comment]
Thanks for confirming. Would you like a PR, or shall I just leave it with you?

**Comment by mike-lischke** [comment]
:-D I have changed it already. Will arrive here with the next patch.

**Comment by NorthNick** [comment]
Wow - fast work! Thank you, and thanks also for the package, which has made my current language server possible,

Nick
