### ISSUE TITLE
How to achieve sql column name auto completion? 

### ISSUE THREAD

**Issue by melin** [mike-lischke/antlr4-c3#65]
example： select na from tb1 a left join tb2 b a.code=b.code。
Enter na, how to get the table name: tb1 and tb2, more complex sql, may contain nesting, how to get the corresponding table name, query field information through the table name.

@mike-lischke

**Comment by mike-lischke** [comment]
This kind of information is something you have to collect. Usually you do some post processing of the input, with help of a symbol table containing possible tables, columns and so on. Check the implementation for MySQL in [MySQL Workbench](https://github.com/mysql/mysql-workbench/blob/8.0/library/parsers/code-completion/mysql-code-completion.cpp) for a way to do that.
