### ISSUE TITLE
Class extends value undefined is not a constructor or null when using yarn pnp and typescript4

### ISSUE THREAD

**Issue by chengchengpei** [mike-lischke/antlr4-c3#72]
More details can be found https://stackoverflow.com/questions/74870072/typeerror-class-extends-value-undefined-is-not-a-constructor-or-null-when-using

I am also trying to use antlr4-c3 in my project too, but got similar errors. I guess my yarn pnp or jest not set up properly.

**Comment by mike-lischke** [comment]
I don't see how this is related to antlr4-c3. Obviously there's no such error for other users, nor have I ever seen it for this lib.
