### ISSUE TITLE
About Typescript Runtime (antlr4s)

### ISSUE THREAD

**Issue by wewoor** [mike-lischke/antlr4-c3#78]
Hi @mike-lischke,

Our ANTLR4 grammar was generated from ANTLR4 v4.12.0. It supports targeting TypeScript directly. However, I noticed in your [document](https://github.com/mike-lischke/antlr4-c3#getting-started) that it requires the antlr4ts runtime. Therefore, I would like to know if it has any effect if we use ANTLR4 v4.12.0, or if it is necessary to use the antlr4ts runtime.

The antlr4ts runtime hasn't been updated for a long time, so we don't use it. I am looking forward to your reply. Thank you.

**Comment by wewoor** [comment]
> 

The [antlr4ts v0.5.0-alpha.4](https://github.com/tunnelvisionlabs/antlr4ts) appears to be using ANTLR 4.9. [TS runtime](https://github.com/mike-lischke/a4tstool) looks good. Is it ready to be used by others?

**Comment by mike-lischke** [comment]
I tried to port antlr4-c3 over to the "new runtime", but failed, due to a number of missing pieces (like no vocabulary). Over time they will certainly be added, but I prefer a runtime which is complete from the start. Btw. antlr4ts also has a few left outs, but they don't matter that much.
