### ISSUE TITLE
Candidate token's follow TokenList is inaccurate when the candidate's origin is ambiguous

### ISSUE THREAD

**Issue by br0nstein** [mike-lischke/antlr4-c3#80]
With the following rules:
```
rule1: LOREM (rule2 | rule3) ;
rule2: IPSUM DOLOR SIT ;
rule3: IPSUM DOLOR AMET ;
```

or

```
rule1: LOREM (IPSUM DOLOR SIT | IPSUM DOLOR AMET) ;
```

Collecting candidates for the input `LOREM IPSUM ^` returns follow set `[SIT]` for candidate token `DOLOR`. It is expected that the follow set be empty, as `SIT` and `AMET` are both valid tokens that may follow.

This repros whenever the candidate token can originate from multiple ATN states. Of course it is recommended when writing ANTLR rules to use left-factoring to prevent ambiguities (e.g. in these example grammars, you wouldn't even be able to get a parse tree with a missing token insertion for `LOREM IPSUM DOLOR` due to the ambiguity), but this isn't always easily possible.

**Comment by mike-lischke** [comment]
Thanks for the report and the PR. A new version is now available.
