### ISSUE TITLE
nameless ScopedSymbol problem

### ISSUE THREAD

**Issue by herny-sandbox** [mike-lischke/antlr4-c3#82]
I'm trying to fill a SymbolTable using a SymbolTableVisitor that extends from AbstractParseTreeVisitor<symbols.SymbolTable>
I found some examples so I'm not having problems to visit classes and functions.

My problem rises in the situation where I want to visit a forloop (my language is similar to java) 
When I'm visiting the for-loop I'm adding a new symbol since we are entering a new block, (ScopedSymbol without name). 
The problem is that seems internally is recording the symbol name with an empty string.
As soon as I visit a second for-loop in sequence is throwing me this exception:
Uncaught DuplicateSymbolError Error: Attempt to add duplicate symbol ''

I'm doing something wrong?, there is another way to add a symbol scope without defining a name for it?
or there is a bug there?

**Comment by mike-lischke** [comment]
You have 2 options here:

1. Give your blocks a unique name (e.g. "#block123").
2. Disable the duplicate symbol name check, by specifying `{ allowDuplicateSymbols: true }` in the symbol table constructor.

**Comment by herny-sandbox** [comment]
I understand. II think I'll go with the first option. thanks!
