### ISSUE TITLE
How to use with plain JavaScript?

### ISSUE THREAD

**Issue by mewim** [mike-lischke/antlr4-c3#85]
I have a JavaScript project where I would like to add autocomplete feature for a variant of openCypher language we defined as a g4 file. I tried to use the latest version of antlr-c3, and it seems `antlr4ng` is required as the runtime. So I proceed with `antlr4ng`, but it seems that it only works with parser and lexer files generated by `antlr4ng-cli`. I tried to set `-Dlanguage=JavaScript`, but I think the generated files does not work as they still import the regular `antlr4` rather than `antlr4ng`. I then generated TypeScript parser and lexer files with `antlr4ng-cli` and used `tsc` to convert them to JavaScript. It seems I can only convert to ES5 as converting to ES6 will throw many errors. After conversion by `tsc` I can import the parser and lexer into my project, but the parser is broken:
```
Uncaught (in promise) TypeError: Class constructor Xt cannot be invoked without 'new'
    at new CypherParser (VM3994 CypherParser.js:2:4937)
    at Proxy.getAutoSuggestTokens (ShellMainView.vue:24:1)
    at Proxy.mounted (ShellMainView.vue:33:1)
    at eval (runtime-core.esm-bundler.js:2675:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:1)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:1)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2655:1)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:325:1)
    at flushJobs (runtime-core.esm-bundler.js:363:1)
```

I am wondering whether what I did makes sense or not and what is the correct way to set this up without using TypeScript?

**Comment by mike-lischke** [comment]
To avoid getting stuck you can always go back one major version, which works with antlr4ts.

Just like with antlr4ts also antlr4ng only works with files generated from their own cli. As such there's not much difference in handling.

Check the tests in this repository, they are using [ES6](https://github.com/mike-lischke/antlr4-c3/blob/master/tests/tsconfig.json#L5)(more precisely ES2022), so if you get errors with the generated files then something with your handling might be wrong. Note: you can avoid most of the module trouble by using a bundler like webpack or esbuild, which can both take JS and TS files and generate either CommonJS or ESM code for a variety of JS versions. Additionally, the resulting package is smaller and usually also faster in execution.

**Comment by mewim** [comment]
I added `ts-loader` and copied your `tsconfig.json` and directly imported the `ts` files into my JavaScript code and it is working now. Thanks for your help.
