### ISSUE TITLE
CodeCompleteCore constructor now references getVocabulary is this correct or should it be vocabulary

### ISSUE THREAD

**Issue by prmiyasaki** [mike-lischke/antlr4-c3#86]
Recently vocabulary was the accessor. But when it changed to getVocabulary, an exception is thrown "function not found".

**Comment by mike-lischke** [comment]
Should be `this.vocabulary = parser.getVocabulary();`, but that requires the latest `antlr4ng` package. Have you updated both in your project?

**Comment by mike-lischke** [comment]
The release is out now.
