### ISSUE TITLE
About using esbuild to building

### ISSUE THREAD

**Issue by HaydenOrz** [mike-lischke/antlr4-c3#90]
Hi, @mike-lischke .
First , thank you for antlr4-c3, it is awesome!

I noticed that you recently changed your build tools and now using esbuild for building the package. The entry file for the latest version of the package is `index.mjs`, this is causing my app build to fail.  The reason for this is that webpack doesn't handle MJS files very well by default.

<img width="1118" alt="image" src="https://github.com/mike-lischke/antlr4-c3/assets/58289241/95c00b0a-9925-493f-bdcd-6cf26293068a">

This is a breaking change.  Consider whether to release a new major version.

**Comment by mike-lischke** [comment]
I didn't think this would be a big problem and you are the first one reporting a problem with that. Unfortunately, I cannot take back a release and later create a new major release with the same code, but I got your objection and will take even more care in the future. Hopefully you can work around this problem this time.

**Comment by HaydenOrz** [comment]
According to SemVer, npm does not believe that there are any breaking changes between versions 3.3.1 and 3.0.1, so it is possible to install to the latest version. I've fixed this by fixing the antlr4-c3 version to 3.1.1. Before that I specified the version as `^3.0.1`. But, as you said, it's not a big problem.

And I noticed that you've done the typescript runtime replacement, which is good news for me.  Right now I'm using antlr4ts as the runtime, but I can't wait to use the new one. What I want to know is if it works stably now.  

By the way, switching to a new runtime is also a breaking change, because I can't just use the new version without switching runtimes.

**Comment by HaydenOrz** [comment]
If you want to release a new major version to fix this, you can try deprecating the npm package with breaking changes. Of course this is not necessary, I just need to be a little more careful with the version of antlr4-c3 to avoid such problems.
