### ISSUE TITLE
Autocompleting empty string causes error

### ISSUE THREAD

**Issue by nchen63** [mike-lischke/antlr4-c3#94]
When the document is empty and I attempt to autocomplete, I get the error `mismatched input '<EOF>'  expecting {...}` where `{...}` is a list of keywords that would be what I'd want to autocomplete the first token with. I realize this error comes from the parser layer. Is there a good way to capture the list of keywords instead of (or in addition to) erroring? 

I could parse the string error, but that's not ideal

**Comment by mike-lischke** [comment]
Fixed by #95
