### ISSUE TITLE
Option to choose the parser rule for which we need the candidates

### ISSUE THREAD

**Issue by harideepan** [mike-lischke/antlr4-c3#98]
As of now, collectCandidates returns the possibe candidates using the parser rule defined at the top. It would be nice to choose which parser rule to be used for collecting candidates. We have multiple top level parser rules for we need to collect the candidates.

**Comment by mike-lischke** [comment]
[collectCandidates](https://github.com/mike-lischke/antlr4-c3/blob/main/src/CodeCompletionCore.ts#L168) has an option context parameter. That might help.

**Comment by harideepan** [comment]
@mike-lischke Thanks for the quick response, I did see that optional context parameter but I misunderstood it to be something else. It works great!
